/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:270bab9f-f978-4866-b51f-93b3aa02aff8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_TPwmsxeEB",
    "aws_user_pools_web_client_id": "5t11s5m69t20jg1ddsv53lj3rq",

    "oauth": {
        "domain": "dapp6583b31e-6583b31e-develop.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://develop.d21qizb84npe5a.amplifyapp.com/",
        "redirectSignOut": "https://localhost:3000/",
        "responseType": "code"
    },
    // https://localhost:3000/, 
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://7ghx2bcrgfeyvi6zx3f24t7di4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-tjywegmaqzdlfalql2at2oa3o4"
};


export default awsmobile;
